### ISSUE TITLE
Square logo looks out of place

### ISSUE THREAD

**Issue by colindean** [metamesh/metamesh.org#43]
The white background on dark background looks like it was plastered there.

![image](https://user-images.githubusercontent.com/197224/94377276-2c470380-00ee-11eb-9d06-c3d010f25f69.png)

It'd be better to use a logo that looks better on a dark background while the image background itself is transparent, but a stopgap is to add some rounded corners on the image. Add this to make it look better:

```css
.navbar-brand img {
    border-radius: 10px;
}
```

After:

![image](https://user-images.githubusercontent.com/197224/94377274-22bd9b80-00ee-11eb-8fef-e3c65f7d38e1.png)

I'd do this myself but I'm not on a machine I can easily test the change right now.

**Comment by benjithaimmortal** [comment]
I agree that the logo wants a light site color scheme. I can ask around to some designer friends, since it would be a very minor change to flip the whites and blacks in the logo and make a 'dark-mode' version. That's probably the ideal, at this point, right?

I'm not sure about the rounded edges, to be honest. It's a very geometric logo and it fits well with the squared white around it (I think it would be great as-is on a light-mode theme). But I can implement any changes that are required!

Another possibility is boxing it in the site's yellow. Doubling down on the square.
<img width="268" alt="Screen Shot 2020-09-28 at 7 29 03 AM" src="https://user-images.githubusercontent.com/12068818/94426927-4dded400-015c-11eb-8f6d-adfc29cf4a2f.png">

**Comment by Protagonistics** [comment]
I think the rounded logo is succificent

**Comment by benjithaimmortal** [comment]
Added to most-recent PR and merged
